### ISSUE TITLE
NuGet Framework dependencies don't match compiled code

### ISSUE THREAD

**Issue by PhilipDaniels** [lvermeulen/Nanophone#9]
Just added Nanophone into a 4.5.2 project (which should work according to the nupkg). I think it installed the lib\4.5 dll, but it gives this error in Visual Studio

![nano1](https://cloud.githubusercontent.com/assets/1809220/16982826/f904a148-4e69-11e6-8371-782dfb428aad.png)

Decompiling the DLL with IL spy shows

```
[assembly: TargetFramework(".NETFramework,Version=v4.6.1", FrameworkDisplayName = ".NET Framework 4.6.1")]
```

I presume this is just a build error, but as an aside - please continue to support the oldest possible framework that's practicable (4.5.xxx) - some of us work in environments with legacy code and OS and .Net installations and customers who simply can't upgrade to the latest and greatest at a whim!

**Comment by lvermeulen** [comment]
@PhilipDaniels .net 451 is fully supported. You might want to use the latest prerelease though, it's been a while (meaning: lots of commits) since version 1.1. Can you try 1.3.1-alpha instead? They have to be marked prerelease because they're depending on other prerelease packages (notably Consul.net 0.6.4.8-alpha2).
